import enum


@enum.unique
class Ingredient(enum.Enum):
    BITTERS = "BITTERS"
    BOURBON_WHISKY = "BOURBON_WHISKY"
    CAMPARI = "CAMPARI"
    CASTER_SUGAR_SYRUP = "CASTER_SUGAR_SYRUP"
    COFFEE_LIQUER = "COFFEE_LIQUER"
    DARK_RUM = "DARK_RUM"
    EGG_WHITE = "EGG_WHITE"
    ESPRESSO = "ESPRESSO"
    GIN = "GIN"
    LEMON_JUICE = "LEMON_JUICE"
    LIME_JUICE = "LIME_JUICE"
    MUSCAVADO_SUGAR_SYRUP = "MUSCAVADO_SUGAR_SYRUP"
    PINAPPLE_JUICE = "PINAPPLE_JUICE"
    RED_VERMOUTH = "RED_VERMOUTH"
    SALT = "SALT"
    SODA_WATER = "SODA_WATER"
    VODKA = "VODKA"
    WHITE_VERMOUTH = "WHITE_VERMOUTH"


@enum.unique
class Cocktail(enum.Enum):
    CAMPARI_SODA = "CAMPARI_SODA"
    ESPRESSO_MARTINI = "ESPRESSO_MARTINI"
    JUNGLE_BIRD = "JUNGLE_BIRD"
    MARTINI = "MARTINI"
    NEGRONI = "NEGRONI"
    OLD_FASHIONED = "OLD_FASHIONED"
    WHISKY_SOUR = "WHISKY_SOUR"
